# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
    # BaseManager load class parameter to service
    manager.class: AppBundle\Entity\Manager\BaseManager
    manager.user.entity: AppBundle\Entity\User

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]


#JMS Serializer
     jms_serializer.object_constructor:
            alias: jms_serializer.doctrine_object_constructor
            public: false

#Listener for Cros Browser request and exceptions to json
     api_exception_subscriber:
            class: AppBundle\EventListener\ApiExceptionSubscriber
            arguments: ['@jms_serializer', '@service_container']
            tags:
                - { name: kernel.event_subscriber }
