# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]


#JMS Serializer
     jms_serializer.object_constructor:
            alias: jms_serializer.doctrine_object_constructor
            public: false
